apiVersion: v1
kind: Pod
metadata:
  name: meupod-azul
  labels:
    name: azul
spec:
  containers:
  - name: site
    image: fabricioveronez/web-page:blue
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: meupod-verde
  labels:
    name: verde
spec:
  containers:
  - name: site
    image: fabricioveronez/web-page:blue
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
